### ISSUE TITLE
bug in update 

### ISSUE THREAD

**Issue by anoosi** [iriven/GeoIPCountry#1]
when i update db its stuck in 127.php and the all ips save in it
the file get bigger to 4,5 mb
and any file after 127.php ignore it and no updated?
![untitled](https://user-images.githubusercontent.com/14188374/30446593-463a3b20-9992-11e7-8e77-44507535b211.png)

**Comment by iriven** [comment]
hello Anoosi
sorry to reply so late to your question. to answer your question, it is not a bug, the files are filled according to a specific algorithm. and during the update all files are overwritten. if a file contains less data, its just because the corresponding IP range originaly contains less data in the sotware77 database .

Regards
